# Site settings
title: Mogelmose.org
description: This GitHub Pages site is powered by Jekyll 👨‍🔬💥🧪
baseurl:
url: https://mogelmose.org

# User settings
username: Steffen Møgelmose
user_description:
user_title:
email: steffen@mogelmose.org
twitter_username: smogelmose
github_username:  smogelmose

# Google-analytics
google-analytics:
  id: "G-V1E68N850R"

exclude: ['package.json', 'src' , 'node_modules']

remote_theme: murraco/jekyll-theme-minimal-resume
